apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shared-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "260"
  labels:
    gitops.tier.group: cloudpak
    gitops.tier.layer: applications
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: tools
    server: https://kubernetes.default.svc
  project: applications
  source:
    path: shared/config/tools/secrets/
    repoURL: https://github.com/venu-nfcu-ibm-azure2/multi-tenancy-gitops-apps.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
