apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-mq-rest-prod-1
  annotations:
    argocd.argoproj.io/sync-wave: "300"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: applications
  source:
    path: mq/environments/prod
    repoURL: https://github.com/venu-nfcu-ibm-azure2/multi-tenancy-gitops-apps.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
